const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
let click;const nodes={};const node=k=>nodes[k]??={innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){}},addEventListener(){},showModal(){},focus(){},scrollIntoView(){},insertAdjacentHTML(_,h){this.innerHTML=h+this.innerHTML}};
const oldSave={name:'Miho',level:3,xp:20,coins:3500,hp:80,energy:60,stamina:20,atk:25,def:21,points:2,items:{blade:true},tech:{step:4,arc:2,ward:1,cinder:2},team:['ren'],missions:{trail:3,courier:1,ruins:2},wins:7,losses:2,bank:100,last:Date.now(),activity:[]};
const env={document:{querySelector:node,addEventListener(k,f){if(k==='click')click=f}},localStorage:{getItem(){return JSON.stringify(oldSave)},setItem(){}},setInterval(){},setTimeout(){},clearTimeout(){},Date,Math,console};vm.createContext(env);
for(const f of ['dist/catalog.js','dist/game.js'])vm.runInContext(fs.readFileSync(f,'utf8'),env);
const run=js=>vm.runInContext(js,env);const act=dataset=>click({target:{closest(){return{dataset}}}});
const catalog=run('GAME_CATALOG');assert.equal(catalog.missions.length,90);assert.equal(catalog.jutsus.length,90);const all=[...catalog.missions,...catalog.jutsus];assert.equal(new Set(all.map(e=>e.id)).size,180);assert.equal(new Set(all.map(e=>e.name)).size,180);assert.equal(new Set(all.map(e=>e.artSheet+':'+e.artIndex)).size,180);
for(const g of catalog.grades)for(const category of ['missions','jutsus']){const entries=catalog[category].filter(e=>e.grade===g.id);assert.equal(entries.length,15);assert(entries.every(e=>e.level===g.level&&e.cost>0&&e.xp>0));assert.equal(new Set(entries.map(e=>e.artIndex)).size,15)}
assert.equal(run('s.tech.step'),4);assert.equal(run('s.missions.ruins'),2);assert.equal(run('s.coins'),3500);assert.equal(run('power().a'),97);assert.equal(run('power().d'),Math.round(21+32+9+6+16*.3));
for(const kind of ['missions','techniques']){act({tab:kind});for(const g of catalog.grades){act({grade:g.id});assert.equal((nodes['#view'].innerHTML.match(/<article class="catalog-row/g)||[]).length,15);assert.equal((nodes['#view'].innerHTML.match(/role="img"/g)||[]).length,15);if(g.level>3)assert(nodes['#view'].innerHTML.includes('Level '+g.level+' required'))}}
run('s=initial()');act({tab:'missions'});act({grade:'S'});const before=run('s.energy');act({mission:'m-s-01'});assert.equal(run('s.energy'),before);assert.equal(run('s.missions["m-s-01"]'),undefined);
act({tab:'techniques'});act({grade:'S'});act({tech:'j-s-01'});assert.equal(run('s.energy'),before);assert.equal(run('s.tech["j-s-01"]'),undefined);
act({tab:'missions'});act({grade:'E'});act({mission:'trail'});assert.equal(run('s.energy'),60);assert.equal(run('s.stamina'),14);assert.equal(run('s.coins'),1245);assert(nodes['#view'].innerHTML.includes('Do this mission again'));act({grade:'D'});assert(!nodes['#view'].innerHTML.includes('id="action-result"'));
run('s.level=16;s.energy=maxEnergy();s.xp=0');act({tab:'techniques'});act({grade:'S'});act({tech:'j-s-01'});assert.equal(run('s.tech["j-s-01"]'),1);assert.equal(run('s.xp'),74);assert.equal(run('lastResults.techniques.grade'),'S');assert(nodes['#view'].innerHTML.includes('Learn this jutsu again'));run('s.tech["j-s-01"]=5;s.energy=maxEnergy()');act({tech:'j-s-01'});assert.equal(run('s.tech["j-s-01"]'),5);assert.equal(run('lastResults.techniques.improved'),false);
run('s.missions["m-s-01"]=5;s.stamina=maxStamina()');act({tab:'missions'});act({grade:'S'});act({mission:'m-s-01'});assert.equal(run('lastResults.missions.coins'),900);
for(const f of ['dist/index.html','dist/style.css','dist/game.js','dist/catalog.js'])assert(fs.existsSync(f));
if(!process.argv.includes('--skip-art'))for(const sheet of new Set(all.map(e=>e.artSheet)))assert(fs.statSync('dist/assets/icons/'+sheet+'.webp').size>1000,'Missing artwork '+sheet);
console.log('PASS: 180 unique entries/icons, 15 per grade, level locks, legacy save/mastery/stats, reward scaling, repeat actions and mastery cap.');

run('s=initial();s.stamina=0;s.energy=60');act({tab:'missions'});act({grade:'E'});act({mission:'trail'});assert.equal(run('s.missions.trail'),undefined);assert(nodes['#view'].innerHTML.includes('Need 6 stamina'));
run('s.stamina=20;s.energy=0');act({mission:'trail'});assert.equal(run('s.stamina'),14);assert.equal(run('s.energy'),0);assert(nodes['#view'].innerHTML.includes('6 Stamina'));
act({tab:'techniques'});act({grade:'E'});act({tech:'step'});assert.equal(run('s.tech.step'),undefined);run('s.energy=60;s.stamina=0');act({tech:'step'});assert.equal(run('s.tech.step'),1);assert.equal(run('s.stamina'),0);assert(run('s.energy')<60);assert(nodes['#view'].innerHTML.includes('Spirit'));
console.log('PASS: missions consume only stamina; jutsus consume only spirit; resource guards and labels agree.');
run('s=initial();s.level=100;s.atk=10000;s.def=10000;s.stamina=20');act({tab:'arena'});
for(let i=0;i<4;i++){act({fight:'0'});assert(run('lastResults.arena.dealt')<=27);assert(run('lastResults.arena.damage')<=27)}
assert.equal(run('rivalState(0).hp'),0);assert.equal(run('lastResults.arena.dealt'),19);const deadStamina=run('s.stamina'),deadCoins=run('s.coins');act({fight:'0'});assert.equal(run('s.stamina'),deadStamina);assert.equal(run('s.coins'),deadCoins);assert(nodes['#view'].innerHTML.includes('This rival is recovering'));
run('rivalState(0).last-=60000;regen()');assert.equal(run('rivalState(0).hp'),2);act({fight:'0'});assert.equal(run('lastResults.arena.dealt'),2);assert.equal(run('rivalState(0).hp'),0);assert.equal(run('rivalState(1).hp'),100);
run('s=initial();s.level=100;s.hp=100;opponents[1].atk=10000');act({fight:'1'});assert.equal(run('lastResults.arena.damage'),27);assert.equal(run('s.hp'),73);run('s.hp=1');act({fight:'1'});assert.equal(run('lastResults.arena.damage'),1);assert.equal(run('s.hp'),0);const downStamina=run('s.stamina');act({fight:'2'});assert.equal(run('s.stamina'),downStamina);act({action:'heal'});assert.equal(run('s.hp'),100);
run('rivalState(0).hp=0;rivalState(0).last-=100*60000;regen()');assert.equal(run('rivalState(0).hp'),100);assert.equal(JSON.parse(run('JSON.stringify(s)')).rivalHealth[0].hp,100);
console.log('PASS: persistent rival HP, 27 damage cap, overkill clamp, knockout guards, regeneration and doctor recovery.');
run('s=initial();s.level=100;s.atk=10000;s.def=10000');act({tab:'arena'});act({fight:'0'});assert.equal(run('s.kills'),0);assert.equal(run('s.deaths'),0);run('rivalState(0).hp=1');act({fight:'0'});assert.equal(run('s.kills'),1);assert.equal(run('rivalState(0).deaths'),1);act({fight:'0'});assert.equal(run('s.kills'),1);run('rivalState(0).last-=60000;regen()');act({fight:'0'});assert.equal(run('s.kills'),2);
run('s.hp=1;s.def=0;s.atk=10000;rivalState(1).hp=1');act({fight:'1'});assert.equal(run('s.kills'),3);assert.equal(run('s.deaths'),1);assert.equal(run('rivalState(1).kills'),1);assert.equal(run('rivalState(1).deaths'),1);act({fight:'1'});assert.equal(run('s.deaths'),1);act({action:'heal'});assert.equal(run('s.deaths'),1);act({tab:'profile'});assert(nodes['#view'].innerHTML.includes('3 Kills · 1 Deaths'));assert(nodes['#power-stats'].innerHTML.includes('KILLS'));
console.log('PASS: lethal damage counts kills/deaths once, including mutual kills; recovery preserves lifetime stats.');
