const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes={},listeners=[];let saved;
function node(k){return nodes[k]??={innerHTML:'',textContent:'',value:'',style:{},dataset:{},classList:{add(){},remove(){},contains(){return false}},querySelector(){return null},querySelectorAll(){return []},appendChild(){},addEventListener(){},setAttribute(){},focus(){},select(){},showModal(){},scrollIntoView(){},insertAdjacentHTML(where,h){this.innerHTML=where==='afterbegin'?h+this.innerHTML:this.innerHTML+h}}}
const old={name:'Miho',level:3,xp:0,coins:5000,hp:80,energy:60,stamina:20,atk:25,def:21,points:8,items:{blade:true,coat:true},tech:{step:3},team:['ren'],missions:{trail:3},wins:7,losses:2,bank:100,last:Date.now(),activity:[]};
const env={globalThis:null,document:{querySelector:node,querySelectorAll(){return[]},createElement:()=>node('created'),body:node('body'),addEventListener(k,f,cap){if(k==='click')listeners.push({f,cap})}},localStorage:{getItem(){return JSON.stringify(saved||old)},setItem(k,v){saved=JSON.parse(v)}},setInterval(){},setTimeout(){},clearTimeout(){},Date,Math,console};env.globalThis=env;vm.createContext(env);
for(const f of ['catalog.js','game.js','systems.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),env);
const run=x=>vm.runInContext(x,env);function click(dataset){let stopped=false;const e={target:{closest:()=>({dataset})},preventDefault(){},stopImmediatePropagation(){stopped=true}};for(const l of [...listeners].sort((a,b)=>!!b.cap-!!a.cap)){if(!stopped)l.f(e)}}
assert.equal(run('s.items.blade'),1);assert.equal(run('s.items.kunai'),10);assert.equal(run('s.missions.trail'),3);assert.equal(run('s.bank'),100);run('setupSystems()');assert.equal(run('s.items.kunai'),10);
// Every top-level view renders without a runtime failure.
for(const t of ['arena','missions','techniques','equipment','team','profile','story','duties','council','gifts','ranks','forum']){click({tab:t});assert(nodes['#view'].innerHTML.length>100,t)}
run('s.coins=10000');assert.equal(run('buyItem("blade",3)'),true);assert.equal(run('s.items.blade'),4);assert.equal(run('buyItem("blade",-1)'),false);assert.equal(run('buyItem("blade",1.5)'),false);assert.equal(run('power().attackSet.find(e=>e.item.id==="blade").n'),2);run('s.items.saber=1');assert.equal(run('power().attackSet.find(e=>e.item.id==="saber").n'),1);
// Mission resource and supply transaction; repeat action takes exactly one charge.
run('s.level=100;s.xp=0;s.stamina=100;s.energy=60;s.items.kunai=3');const stamina=run('s.stamina'),coins=run('s.coins');click({mission:'trail'});assert.equal(run('s.stamina'),stamina-6);assert.equal(run('s.energy'),60);assert.equal(run('s.items.kunai'),2);assert.equal(run('s.coins'),coins+45);
run('s.items.kunai=0;s.autoBuy=false');const before=run('s.stamina');assert.equal(run('performMission("trail")'),false);assert.equal(run('s.stamina'),before);run('s.autoBuyUnlocked=true;s.autoBuy=true;s.coins=14');assert.equal(run('performMission("trail")'),false);assert.equal(run('s.coins'),14);run('s.coins=100');assert.equal(run('performMission("trail")'),true);assert.equal(run('s.items.kunai'),0);assert.equal(run('s.coins'),130); // Base reward 45 less supply 15; this run reaches Expert.
// All stat allocation costs and maximum values, doctor and full-rest overfill.
run('s.points=8');for(const id of ['atk','def','healthBonus','spiritBonus'])assert.equal(run(`allocateStat('${id}')`),true);assert.equal(run("allocateStat('staminaBonus')"),true);assert.equal(run('s.points'),2);assert.equal(run('maxHealth()'),105);run('s.hp=0;s.coins=1000');click({action:'heal'});assert.equal(run('s.hp'),105);run('s.energy=Math.floor(maxEnergy()*1.25);s.stamina=0');const over=run('s.energy');click({action:'rest'});assert.equal(run('s.energy'),over);run('s.last-=60000;regen()');assert.equal(run('s.energy'),over);
// Packs, gifts, recruitment and commendations cannot be claimed twice.
assert.equal(run("recruit('aya')"),true);assert.equal(run("recruit('aya')"),false);assert.equal(run('claimPack()'),true);assert.equal(run('claimPack()'),false);assert.equal(run('s.energy'),Math.floor(run('maxEnergy()')*1.25));run('s.gifts.receivedAt-=23*HOUR');assert.equal(run('claimPack()'),true);assert.equal(run('freeGift()'),true);assert.equal(run('freeGift()'),false);assert.equal(run("systemAction('commend','3')"),true);assert.equal(run("systemAction('commend','3')"),false);assert.equal(run("systemAction('sendPack','aya')"),true);assert.equal(run("systemAction('sendPack','aya')"),false);
// Timed duties and sequential story chapters.
run('s.stamina=100;s.coins=10000;s.autoBuy=true');assert.equal(run("startDuty('patrol')"),true);assert.equal(run("startDuty('patrol')"),false);assert.equal(run('claimDuty()'),false);run('s.duty.ends=Date.now()-1');assert.equal(run('claimDuty()'),true);assert.equal(run('claimDuty()'),false);assert.equal(run('s.dutiesDone'),1);
for(let i=0;i<5;i++){run('s.stamina=100');assert.equal(run("completeStory('siege')"),true)}assert.equal(run("completeStory('siege')"),false);assert.equal(run('s.story.siege'),5);
// Forum text is escaped, retained, and replies stay attached to their topic.
node('#forum-title').value='<script>bad</script>';node('#forum-body').value='<img onerror=bad>';assert.equal(run("systemAction('post')"),true);run("tab='forum';render()");assert(!nodes['#view'].innerHTML.includes('<img onerror'));assert(nodes['#view'].innerHTML.includes('&lt;img'));node('#forum-reply').value='Reply';assert.equal(run("systemAction('reply')"),true);assert.equal(run('s.forum[0].replies.length'),1);run('save()');assert.equal(saved.story.siege,5);assert.equal(saved.items.blade,4);assert.equal(saved.forum.length,1);
console.log('PASS: all 12 screens, save migration, bulk inventory/loadouts, atomic mission supplies, five stat upgrades, hospital, overfill, gift cooldowns, recruitment, duties, chapters, forum escaping and persistence.');
// Interactive duty engine: timers pause at encounters, including time spent offline.
vm.runInContext(fs.readFileSync('dist/duties.js','utf8'),env);
run('s.duty=null;s.hp=maxHealth();s.stamina=100;s.energy=100;s.atk=10000;s.def=10000;s.level=3;s.tech.step=1');assert.equal(run("startDuty('patrol')"),true);assert.equal(run('s.duty.event.type'),'route');const paid=run('s.stamina');run('s.duty.lastTick-=1000000;advanceDuty()');assert.equal(run('s.duty.elapsed'),0);assert.equal(run('claimDuty()'),false);assert.equal(run("dutyChoice('cautious')"),true);assert.equal(run('s.duty.cautious'),true);run('s.duty.lastTick-=200000;advanceDuty()');assert.equal(run('s.duty.elapsed'),105000);assert.equal(run('s.duty.event.type'),'ambush');const hpBefore=run('s.hp');run('s.duty.lastTick-=9999999;advanceDuty()');assert.equal(run('s.hp'),hpBefore);assert.equal(run('s.duty.elapsed'),105000);
const killsBefore=run('s.kills'),spiritBefore=run('s.energy');assert.equal(run("dutyChoice('jutsu')"),true);assert.equal(run('s.energy'),spiritBefore-8);assert.equal(run('s.duty.event.hp'),19);assert(run('s.hp')>=hpBefore-27);run("dutyChoice('fight')");assert.equal(run('s.kills'),killsBefore+1);assert.equal(run('s.duty.event'),null);assert.equal(run('s.stamina'),paid);run('s.duty.lastTick-=200000;advanceDuty()');assert.equal(run('s.duty.event.type'),'discovery');run('s.energy=0');assert.equal(run("dutyChoice('investigate')"),false);assert.equal(run("dutyChoice('continue')"),true);run('s.duty.lastTick-=200000;advanceDuty()');assert.equal(run('s.duty.elapsed'),300000);const earned=run('s.coins');assert.equal(run('claimDuty()'),true);assert.equal(run('s.coins'),earned+140);assert.equal(run('claimDuty()'),false);
// Death records once, kills can coincide, and failed/abandoned duty has no reward.
run('s.stamina=100;s.hp=1');assert.equal(run("startDuty('archive')"),true);run("dutyChoice('bold');s.duty.lastTick-=400000;advanceDuty();s.duty.event.hp=1");const deaths=run('s.deaths'),coinsFail=run('s.coins');run("dutyChoice('fight')");assert.equal(run('s.duty'),null);assert.equal(run('s.deaths'),deaths+1);assert.equal(run('s.coins'),coinsFail);assert.equal(run('s.lastDuty.success'),false);assert.equal(run("dutyChoice('fight')"),false);assert.equal(run("startDuty('patrol')"),false);
run('s.hp=maxHealth();s.stamina=100');run("startDuty('escort');dutyChoice('bold');s.duty.lastTick-=700000;advanceDuty()");env.Math=Object.create(Math);env.Math.random=()=>0;const evasionHp=run('s.hp');assert.equal(run("dutyChoice('evade')"),true);assert.equal(run('s.hp'),evasionHp);assert.equal(run('s.duty.event'),null);run("dutyChoice('retreat')");assert.equal(run('s.duty'),null);
// Existing running duties migrate without losing progress or forcing new encounters.
run("s.duty={id:'patrol',ends:Date.now()-1};migrateDuty()");assert.equal(run('s.duty.stage'),3);assert.equal(run('claimDuty()'),true);run("tab='duties';render()");assert(nodes['#view'].innerHTML.includes('LIVE VILLAGE DUTIES'));run("startDuty('patrol');render()");assert(nodes['#view'].innerHTML.includes('role="progressbar"'));assert(nodes['#view'].innerHTML.includes('Choose your approach'));run('save()');assert.equal(saved.duty.event.type,'route');
console.log('PASS: interactive duties, paused/offline checkpoints, spirit choices, 27-HP cap, kills/deaths, single-claim rewards, retreat and legacy migration.');
